# Generated by Django 3.1.3 on 2021-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description. so the real description can be added here whenever you want.'),
            preserve_default=False,
        ),
    ]
